import readline from 'readline';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '.env') });


const TOOLS = [
  {
    name: "list_companies",
    description: "Retrieve a list of all registered companies. Useful to check existing companies and find their company_id before creating placement drives or performing other updates.",
    inputSchema: {
      type: "object",
      properties: {}
    }
  },
  {
    name: "search_companies",
    description: "Search registered companies by name. Call this tool before creating a drive, setups, or student placement to get the correct company_id instead of inventing one. If multiple companies match, ask the user to clarify.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Name prefix or search term" }
      }
    }
  },
  {
    name: "get_company",
    description: "Get details for a specific company by its company_id.",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Company ID" }
      },
      required: ["company_id"]
    }
  },
  {
    name: "create_company",
    description: "Create a new company record. Before calling this, check if the company already exists using search_companies. DO NOT supply company_id (it is auto-generated by the database). To register a company alongside its placement drive and eligible branches in one action, use setup_company instead.",
    inputSchema: {
      type: "object",
      properties: {
        company_name: { type: "string", description: "Company name" }
      },
      required: ["company_name"]
    }
  },
  {
    name: "update_company",
    description: "Update an existing company name by company_id. Caller must obtain the valid company_id first using search_companies.",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Company ID to update" },
        company_name: { type: "string", description: "New company name" }
      },
      required: ["company_id", "company_name"]
    }
  },
  {
    name: "delete_company",
    description: "Delete a company by company_id. Fails if the company has dependent placement drives. Obtain the company_id first using search_companies.",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Company ID to delete" }
      },
      required: ["company_id"]
    }
  },
  // drives
  {
    name: "list_drives",
    description: "List all placement drives. Useful to check existing drives and retrieve their drive_id.",
    inputSchema: {
      type: "object",
      properties: {}
    }
  },
  {
    name: "search_drives",
    description: "Search and filter placement drives by company, role, ctc, dates, or branch. Call this first to obtain the correct drive_id before modifying drives, adding branches, or placing students. Note: branch must be one of: AIDS, CE, ECE, ENTC, IT.",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Filter by Company ID" },
        company_name: { type: "string", description: "Filter by Company Name" },
        role: { type: "string", description: "Filter by role title" },
        min_ctc: { type: "number", description: "Minimum CTC (LPA) as numeric value" },
        max_ctc: { type: "number", description: "Maximum CTC (LPA) as numeric value" },
        start_date: { type: "string", description: "Start date (YYYY-MM-DD)" },
        end_date: { type: "string", description: "End date (YYYY-MM-DD)" },
        branch: { type: "string", description: "Filter by eligible branch (AIDS, CE, ECE, ENTC, IT)" }
      }
    }
  },
  {
    name: "get_drive",
    description: "Get details of a specific placement drive by its drive_id.",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID" }
      },
      required: ["drive_id"]
    }
  },
  {
    name: "get_company_drives",
    description: "Get all placement drives for a particular company_id.",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Company ID" }
      },
      required: ["company_id"]
    }
  },
  {
    name: "create_drive",
    description: "Create a new placement drive. DO NOT supply drive_id (auto-generated by the database). You must search for the company first to obtain the correct company_id. Numbers MUST be strictly numeric (no units or symbols like 'LPA', '%', or 'CGPA'). E.g., ctc: 9.5 (NOT '9.5 LPA'), eligibility_10th: 68 (NOT '68%'), eligibility_12th: 70 (NOT '70%'), eligibility_cgpa: 8.5 (NOT '8.5 CGPA').",
    inputSchema: {
      type: "object",
      properties: {
        company_id: { type: "integer", description: "Company ID (required)" },
        visiting_date: { type: "string", description: "Date of visit (YYYY-MM-DD)" },
        role: { type: "string", description: "Job profile title" },
        jd_link: { type: "string", description: "JD link URL" },
        ctc: { type: "number", description: "CTC in LPA (number only, e.g. 9.5)" },
        eligibility_10th: { type: "integer", description: "10th min percentage (number only, e.g. 68)" },
        eligibility_12th: { type: "integer", description: "12th min percentage (number only, e.g. 70)" },
        eligibility_cgpa: { type: "number", description: "CGPA min criteria (number only, e.g. 8.5)" },
        eligibility_backlog: { type: "string", description: "Backlog criteria" }
      },
      required: ["company_id"]
    }
  },
  {
    name: "update_drive",
    description: "Update an existing placement drive details. DO NOT supply drive_id in the body. You must obtain the drive_id first using search_drives. Numbers MUST be strictly numeric (no units like 'LPA', '%', or 'CGPA'). E.g., ctc: 10.5 (NOT '10.5 LPA'), eligibility_10th: 75 (NOT '75%'), eligibility_12th: 75 (NOT '75%'), eligibility_cgpa: 9.0 (NOT '9.0 CGPA').",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID to update (required)" },
        company_id: { type: "integer", description: "Company ID" },
        visiting_date: { type: "string", description: "Date of visit (YYYY-MM-DD)" },
        role: { type: "string", description: "Job profile title" },
        jd_link: { type: "string", description: "JD link URL" },
        ctc: { type: "number", description: "CTC in LPA (number only, e.g. 9.5)" },
        eligibility_10th: { type: "integer", description: "10th min percentage (number only, e.g. 68)" },
        eligibility_12th: { type: "integer", description: "12th min percentage (number only, e.g. 70)" },
        eligibility_cgpa: { type: "number", description: "CGPA min criteria (number only, e.g. 8.5)" },
        eligibility_backlog: { type: "string", description: "Backlog criteria" }
      },
      required: ["drive_id"]
    }
  },
  {
    name: "delete_drive",
    description: "Delete a placement drive by drive_id. Fails if students are placed in it. Obtain the drive_id first using search_drives.",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID to delete" }
      },
      required: ["drive_id"]
    }
  },
  // branches
  {
    name: "get_drive_branches",
    description: "Get eligible branches mapped to a drive_id.",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID" }
      },
      required: ["drive_id"]
    }
  },
  {
    name: "add_branch",
    description: "Add an eligible branch to a drive_id. Branch must be one of: AIDS, CE, ECE, ENTC, IT (case-insensitive). Obtain the drive_id first using search_drives.",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID" },
        branch: { type: "string", description: "Branch (AIDS, CE, ECE, ENTC, IT)" }
      },
      required: ["drive_id", "branch"]
    }
  },
  {
    name: "remove_branch",
    description: "Remove an eligible branch from a drive_id. Branch must be one of: AIDS, CE, ECE, ENTC, IT (case-insensitive).",
    inputSchema: {
      type: "object",
      properties: {
        drive_id: { type: "integer", description: "Drive ID" },
        branch: { type: "string", description: "Branch (AIDS, CE, ECE, ENTC, IT)" }
      },
      required: ["drive_id", "branch"]
    }
  },
  // students
  {
    name: "list_students",
    description: "List all students.",
    inputSchema: {
      type: "object",
      properties: {}
    }
  },
  {
    name: "search_students",
    description: "Search and filter students by name, first/last name (student_first_name, student_last_name), email, department, placement status, or company. Call this to look up a student before placing or updating them.",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Search by student full name or general search query" },
        first_name: { type: "string", description: "Search by student first name" },
        last_name: { type: "string", description: "Search by student last name" },
        student_first_name: { type: "string", description: "Search by student first name" },
        student_last_name: { type: "string", description: "Search by student last name" },
        email: { type: "string", description: "Search by email" },
        department: { type: "string", description: "Filter by department (AIDS, CE, ECE, ENTC, IT)" },
        placed: { type: "string", enum: ["true", "false"], description: "Filter by placement status" },
        company_name: { type: "string", description: "Filter by company placed in" },
        drive_id: { type: "integer", description: "Filter by drive ID placed in" }
      }
    }
  },
  {
    name: "get_student",
    description: "Get specific student details by student_id.",
    inputSchema: {
      type: "object",
      properties: {
        student_id: { type: "integer", description: "Student ID" }
      },
      required: ["student_id"]
    }
  },
  {
    name: "create_student",
    description: "Create a new student record. DO NOT supply student_id. Department must be one of: AIDS, CE, ECE, ENTC, IT. Placement operations should be performed using record_placement or place_student, not directly during student creation.",
    inputSchema: {
      type: "object",
      properties: {
        student_first_name: { type: "string", description: "First name" },
        student_last_name: { type: "string", description: "Last name" },
        email: { type: "string", description: "Email address" },
        department: { type: "string", description: "Department (AIDS, CE, ECE, ENTC, IT)" },
        placement_date: { type: "string", description: "Date of placement (YYYY-MM-DD)" },
        placed_drive_id: { type: "integer", description: "Drive ID placed in" }
      },
      required: ["student_first_name", "student_last_name"]
    }
  },
  {
    name: "update_student",
    description: "Update details of an existing student by student_id. DO NOT use this tool to place or unplace a student (placed_drive_id or placement_date). For placement updates, always call record_placement, place_student, or unplace_student instead.",
    inputSchema: {
      type: "object",
      properties: {
        student_id: { type: "integer", description: "Student ID to update" },
        student_first_name: { type: "string", description: "First name" },
        student_last_name: { type: "string", description: "Last name" },
        email: { type: "string", description: "Email address" },
        department: { type: "string", description: "Department (AIDS, CE, ECE, ENTC, IT)" },
        placement_date: { type: "string", description: "Date of placement (YYYY-MM-DD)" },
        placed_drive_id: { type: "integer", description: "Drive ID placed in" }
      },
      required: ["student_id"]
    }
  },
  {
    name: "delete_student",
    description: "Delete a student record by student_id. Obtain the student_id first using search_students.",
    inputSchema: {
      type: "object",
      properties: {
        student_id: { type: "integer", description: "Student ID to delete" }
      },
      required: ["student_id"]
    }
  },
  // placement
  {
    name: "record_placement",
    description: "Atomically find a student by their first & last name (or full name/ID), resolve the placement drive for the company (matching the role if available, or automatically falling back to whatever role/drive that company has), and update the students table. If placement_date is omitted, it automatically defaults to the current date (today). Use this primary tool whenever an announcement message states that a student has been placed or got an internship/PPO.",
    inputSchema: {
      type: "object",
      properties: {
        student_first_name: { type: "string", description: "Student first name" },
        student_last_name: { type: "string", description: "Student last name" },
        student_name: { type: "string", description: "Full student name (e.g. 'Neeraj Gogate')" },
        student_id: { type: "integer", description: "Optional Student ID if already known" },
        company_name: { type: "string", description: "Company name where student is placed (e.g. 'Atomberg Technologies')" },
        role: { type: "string", description: "Role or job title if mentioned (e.g. 'Hardware Intern' or 'Software Engineer')" },
        placement_date: { type: "string", description: "Placement date (YYYY-MM-DD or DD/MM/YYYY). Defaults to today's date if not specified." }
      },
      required: ["company_name"]
    }
  },
  {
    name: "place_student",
    description: "Mark a student as placed in a drive by exact student_id and drive_id. If placement_date is not specified, it defaults to the current date.",
    inputSchema: {
      type: "object",
      properties: {
        student_id: { type: "integer", description: "Student ID" },
        drive_id: { type: "integer", description: "Drive ID" },
        placement_date: { type: "string", description: "Date placed (YYYY-MM-DD). Defaults to today's date if not specified." }
      },
      required: ["student_id", "drive_id"]
    }
  },
  {
    name: "unplace_student",
    description: "Unplace a student from their current drive. Done atomically in a transaction. You MUST search for the student first to obtain the correct student_id. Fails if the student is not placed.",
    inputSchema: {
      type: "object",
      properties: {
        student_id: { type: "integer", description: "Student ID" }
      },
      required: ["student_id"]
    }
  },
  // reporting
  {
    name: "get_placement_report",
    description: "Retrieve a complete relational report of placed students, their placement drives, and companies.",
    inputSchema: {
      type: "object",
      properties: {}
    }
  },
  {
    name: "get_branch_statistics",
    description: "Retrieve branch-wise placement statistics (placed count, average ctc, max ctc).",
    inputSchema: {
      type: "object",
      properties: {}
    }
  },
  // company setup
  {
    name: "setup_company",
    description: "Atomically register or update a company, create/update its placement drive, and map its eligible branches in a single transaction. Use this tool when a company visiting / drive announcement is received. Supports 'All Branches' or specific branches (AIDS, CE, ECE, ENTC, IT). Numbers for CTC and eligibility are automatically parsed (e.g. '12 LPA' -> 12, '6.74 CGPA' -> 6.74, '60%' -> 60). Date formats like DD/MM/YYYY or YYYY-MM-DD are automatically supported.",
    inputSchema: {
      type: "object",
      properties: {
        company_name: { type: "string", description: "Company Name (required)" },
        visiting_date: { type: "string", description: "Date of visit or deadline (YYYY-MM-DD or DD/MM/YYYY)" },
        role: { type: "string", description: "Job profile title (e.g. 'Software Engineer')" },
        jd_link: { type: "string", description: "JD Link URL" },
        ctc: { type: "number", description: "CTC in LPA as numeric value (e.g. 12 or 9.5)" },
        eligibility_10th: { type: "integer", description: "10th min percentage (e.g. 60)" },
        eligibility_12th: { type: "integer", description: "12th min percentage (e.g. 60)" },
        eligibility_cgpa: { type: "number", description: "CGPA min criteria (e.g. 6.74)" },
        eligibility_backlog: { type: "string", description: "Backlog criteria" },
        branches: {
          type: "array",
          items: { type: "string" },
          description: "Eligible branches (e.g. ['All Branches'] or ['AIDS', 'CE', 'ECE', 'ENTC', 'IT'])"
        }
      },
      required: ["company_name"]
    }
  }
];

const BASE_URL = process.env.BACKEND_URL || 'http://127.0.0.1:5000/api';

async function callApi(path, method = 'GET', body = null) {
  try {
    const options = { method };
    const headers = {};
    if (process.env.API_KEY) {
      headers['X-API-Key'] = process.env.API_KEY;
    }
    if (body) {
      headers['Content-Type'] = 'application/json';
      options.body = JSON.stringify(body);
    }
    options.headers = headers;
    const response = await fetch(`${BASE_URL}${path}`, options);
    const data = await response.json();
    return { status: response.status, data };
  } catch (error) {
    return { status: 500, data: { error: `Failed to connect to backend: ${error.message}` } };
  }
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

rl.on('line', async (line) => {
  if (!line.trim()) return;
  try {
    const request = JSON.parse(line);
    if (request.method === 'initialize') {
      const response = {
        jsonrpc: "2.0",
        id: request.id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: {
            tools: {}
          },
          serverInfo: {
            name: "placement-monitoring-tools",
            version: "1.0.0"
          }
        }
      };
      process.stdout.write(JSON.stringify(response) + '\n');
    } else if (request.method === 'tools/list') {
      const response = {
        jsonrpc: "2.0",
        id: request.id,
        result: {
          tools: TOOLS
        }
      };
      process.stdout.write(JSON.stringify(response) + '\n');
    } else if (request.method === 'tools/call') {
      const { name, arguments: args } = request.params;
      let apiResult = null;
      
      switch (name) {
        case 'list_companies':
          apiResult = await callApi('/companies/list');
          break;
        case 'search_companies':
          apiResult = await callApi('/companies/search?name=' + encodeURIComponent(args.name || ''));
          break;
        case 'get_company':
          apiResult = await callApi('/companies/' + args.company_id);
          break;
        case 'create_company':
          apiResult = await callApi('/companies', 'POST', { company_name: args.company_name });
          break;
        case 'update_company':
          apiResult = await callApi('/companies/' + args.company_id, 'PUT', { company_name: args.company_name });
          break;
        case 'delete_company':
          apiResult = await callApi('/companies/' + args.company_id, 'DELETE');
          break;
        case 'list_drives':
          apiResult = await callApi('/drives');
          break;
        case 'search_drives': {
          const params = new URLSearchParams();
          for (const [k, v] of Object.entries(args || {})) {
            if (v !== undefined && v !== null) params.append(k, v);
          }
          apiResult = await callApi('/drives/search?' + params.toString());
          break;
        }
        case 'get_drive':
          apiResult = await callApi('/drives/' + args.drive_id);
          break;
        case 'get_company_drives':
          apiResult = await callApi('/companies/' + args.company_id + '/drives');
          break;
        case 'create_drive':
          apiResult = await callApi('/drives', 'POST', args);
          break;
        case 'update_drive':
          apiResult = await callApi('/drives/' + args.drive_id, 'PUT', args);
          break;
        case 'delete_drive':
          apiResult = await callApi('/drives/' + args.drive_id, 'DELETE');
          break;
        case 'get_drive_branches':
          apiResult = await callApi('/drives/' + args.drive_id + '/branches');
          break;
        case 'add_branch':
          apiResult = await callApi('/drives/' + args.drive_id + '/branches', 'POST', { branch: args.branch });
          break;
        case 'remove_branch':
          apiResult = await callApi('/drives/' + args.drive_id + '/branches/' + encodeURIComponent(args.branch), 'DELETE');
          break;
        case 'list_students':
          apiResult = await callApi('/students/list');
          break;
        case 'search_students': {
          const params = new URLSearchParams();
          for (const [k, v] of Object.entries(args || {})) {
            if (v !== undefined && v !== null) params.append(k, v);
          }
          apiResult = await callApi('/students/search?' + params.toString());
          break;
        }
        case 'get_student':
          apiResult = await callApi('/students/' + args.student_id);
          break;
        case 'create_student':
          apiResult = await callApi('/students', 'POST', args);
          break;
        case 'update_student':
          apiResult = await callApi('/students/' + args.student_id, 'PUT', args);
          break;
        case 'delete_student':
          apiResult = await callApi('/students/' + args.student_id, 'DELETE');
          break;
        case 'record_placement':
          apiResult = await callApi('/students/record-placement', 'POST', args);
          break;
        case 'place_student':
          apiResult = await callApi('/students/place', 'POST', args);
          break;
        case 'unplace_student':
          apiResult = await callApi('/students/unplace', 'POST', args);
          break;
        case 'get_placement_report':
          apiResult = await callApi('/reports/placements');
          break;
        case 'get_branch_statistics':
          apiResult = await callApi('/reports/branches-stats');
          break;
        case 'setup_company':
          apiResult = await callApi('/companies/setup', 'POST', args);
          break;
        default:
          apiResult = { status: 404, data: { error: `Tool ${name} not found` } };
      }

      const isError = apiResult.status >= 400;
      const response = {
        jsonrpc: "2.0",
        id: request.id,
        result: {
          content: [
            {
              type: "text",
              text: JSON.stringify(apiResult.data)
            }
          ],
          isError
        }
      };
      process.stdout.write(JSON.stringify(response) + '\n');
    }
  } catch (err) {
    const response = {
      jsonrpc: "2.0",
      id: null,
      error: {
        code: -32603,
        message: err.message
      }
    };
    process.stdout.write(JSON.stringify(response) + '\n');
  }
});
